# =================================
# = Server
# =================================
server:
  port: 8080

# =================================
# = Spring
# =================================
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/dbpdv
        username: postgres
        password: admin
        type: com.zaxxer.hikari.HikariDataSource
    jpa: 
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        show-sql: true
        properties:
            hibernate: 
                # update atualiza os schemas de banco de dados, none, validate, update, create, create-drop
                ddl-auto: update
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher


# =================================
# = Logging - INFO - TRACE - DEBUG - ERROR
# =================================
logging:
    level:
        org-springframework: INFO
        # org-flywaydb: INFO